<a href="https://colab.research.google.com/github/rajimitara/DS-practice/blob/master/pytorch_neural_network_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
from torch.nn import functional as F

import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv('https://raw.githubusercontent.com/rajimitara/buildModel-and-Mlflow/main/data_training.csv')


In [3]:
dataset.tail()


id_customer  default  ...  n_transactions_last_month  volume_last_month
7495         7511        0  ...                         10          38.889220
7496         7512        0  ...                          4           1.109195
7497         7513        0  ...                         12           0.468105
7498         7514        0  ...                         18           5.043224
7499         7516        0  ...                         13           0.045109

[5 rows x 10 columns]

In [4]:
dataset.describe()

id_customer     default  ...  n_transactions_last_month  volume_last_month
count  7500.000000  7500.00000  ...                7500.000000        7500.000000
mean   3749.702933     0.10000  ...                  10.025867          72.122778
std    2165.554161     0.30002  ...                   3.161708         713.412589
min       0.000000     0.00000  ...                   0.000000           0.000000
25%    1874.750000     0.00000  ...                   8.000000           0.349632
50%    3749.500000     0.00000  ...                  10.000000           2.031870
75%    5624.250000     0.00000  ...                  12.000000          12.590326
max    7516.000000     1.00000  ...                  24.000000       36103.995498

[8 rows x 10 columns]

In [5]:
X = dataset.iloc[:, 2:].values
y = dataset.iloc[:,1].values

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =.20,random_state=0)

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [22]:
Xtrain_ = torch.from_numpy(X_train).float()
Xtest_ = torch.from_numpy(X_test).float()

In [23]:
Xtrain_

tensor([[ 0.4631, -0.5743,  0.9904,  ..., -0.9907, -0.3294, -0.0603],
        [ 1.1819, -0.4887, -1.0097,  ..., -0.7615, -0.3294, -0.1172],
        [-1.1014, -0.5743, -1.0097,  ..., -0.4411, -0.9642, -0.1056],
        ...,
        [ 1.6048, -0.9169, -1.0097,  ...,  0.1280, -0.3294,  0.0137],
        [ 1.6893, -1.5878,  0.9904,  ..., -0.9591,  3.1616, -0.1169],
        [-0.4249, -0.1603, -1.0097,  ..., -0.2786, -1.2815, -0.1068]])

In [24]:
ytrain_ = torch.from_numpy(y_train)
ytest_ = torch.from_numpy(y_test)

In [25]:
ytrain_

tensor([0, 0, 0,  ..., 0, 0, 0])

In [26]:
Xtrain_.shape, ytrain_.shape

(torch.Size([6000, 8]), torch.Size([6000]))

In [27]:
Xtest_.shape, ytest_.shape

(torch.Size([1500, 8]), torch.Size([1500]))

In [42]:
input_size=8
output_size=2
hidden_size=10

In [43]:
class Net(nn.Module):
   def __init__(self):
       super(Net, self).__init__()
       self.fc1 = torch.nn.Linear(input_size, hidden_size)
       self.fc2 = torch.nn.Linear(hidden_size, hidden_size)
       self.fc3 = torch.nn.Linear(hidden_size, output_size)


   def forward(self, X):
       X = torch.relu((self.fc1(X)))
       X = torch.relu((self.fc2(X)))
       X = self.fc3(X)

       return F.log_softmax(X,dim=1)

In [44]:
model = Net()


In [45]:
import torch.optim as optim
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
loss_fn = nn.NLLLoss()

In [46]:
epochs = 100


In [47]:
for epoch in range(epochs):
   optimizer.zero_grad()
   Ypred = model(Xtrain_)
   loss = loss_fn(Ypred,  ytrain_)
   loss.backward()
   optimizer.step()
   print('Epoch',epoch, 'loss',loss.item())

Epoch 0 loss 0.7249419093132019
Epoch 1 loss 0.6926116347312927
Epoch 2 loss 0.6575697660446167
Epoch 3 loss 0.6203613877296448
Epoch 4 loss 0.581641435623169
Epoch 5 loss 0.5422642230987549
Epoch 6 loss 0.503386378288269
Epoch 7 loss 0.4663829803466797
Epoch 8 loss 0.4325757324695587
Epoch 9 loss 0.40324822068214417
Epoch 10 loss 0.379375696182251
Epoch 11 loss 0.3615891933441162
Epoch 12 loss 0.3497873842716217
Epoch 13 loss 0.3432278633117676
Epoch 14 loss 0.3406522274017334
Epoch 15 loss 0.34038883447647095
Epoch 16 loss 0.3408510684967041
Epoch 17 loss 0.34084850549697876
Epoch 18 loss 0.3396003544330597
Epoch 19 loss 0.3368678092956543
Epoch 20 loss 0.3327401876449585
Epoch 21 loss 0.32756197452545166
Epoch 22 loss 0.32175201177597046
Epoch 23 loss 0.31571465730667114
Epoch 24 loss 0.3099108636379242
Epoch 25 loss 0.30464380979537964
Epoch 26 loss 0.3001099228858948
Epoch 27 loss 0.29639264941215515
Epoch 28 loss 0.29351806640625
Epoch 29 loss 0.2913835644721985
Epoch 30 loss 0.2

In [48]:
list(model.parameters())

[Parameter containing:
 tensor([[-4.7720e-02, -1.8021e-01,  2.3253e-02,  3.9389e-02,  3.7898e-02,
          -8.0722e-02,  4.4313e-04, -1.5172e+00],
         [-5.9666e-02,  4.6477e-02, -1.4066e-02, -7.7271e-02, -6.3147e-03,
          -1.1119e-01,  3.0782e-02, -7.9491e-01],
         [-8.0310e-02, -1.0845e-01, -6.6743e-03,  4.2425e-04, -2.7080e-02,
          -4.1895e-02, -1.9653e-02, -9.8755e-01],
         [-1.0126e-01, -1.9774e-01, -7.1519e-02,  1.7291e-01,  1.2950e-02,
           1.4557e-02, -5.0437e-02, -6.0235e-01],
         [ 3.0951e-01, -1.5368e-01,  1.0499e-01,  1.2032e-01,  1.7002e-01,
          -1.6335e-01,  2.2171e-01, -4.5931e-01],
         [-8.6656e-02, -5.0303e-01,  5.0244e-02,  3.0603e-01,  3.9032e-02,
          -2.5225e-01,  1.6992e-02, -2.1472e-01],
         [ 1.2138e-01, -6.3360e-02, -1.6369e-03, -1.0589e-01, -8.6412e-03,
          -1.0383e-01, -1.7798e-03, -4.8876e-01],
         [ 1.7019e-01, -8.0109e-02, -1.4375e-01, -2.3419e-01, -4.3312e-02,
          -6.6273e-01, -3.0

In [49]:
torch.from_numpy(sc.transform(np.array([[99,154,0,1,3,61.10828509499128,19,108.12240555679085]]))).float()

tensor([[ 1.7316,  0.4821, -1.0097,  1.9907,  0.7074,  2.0874,  2.8443,  0.0790]])

In [50]:
new_classifier_inference1 = model(torch.from_numpy(sc.transform(np.array([[99,154,0,1,3,61.10828509499128,19,108.12240555679085]]))).float())
new_classifier_inference1

tensor([[-0.4250, -1.0607]], grad_fn=<LogSoftmaxBackward0>)

In [51]:
_, predicted_20_40000 = torch.max(new_classifier_inference1.data,-1)
predicted_20_40000

tensor([0])

In [56]:
new_classifier_training = model(torch.from_numpy(sc.transform(np.array([[98,97,1,0,1,4.832334122511638,7,282.97659001640096]]))).float())
new_classifier_training

tensor([[-0.7443, -0.6445]], grad_fn=<LogSoftmaxBackward0>)

In [57]:
_, predicted_training= torch.max(new_classifier_training.data,-1)
predicted_training

tensor([1])

In [58]:
torch.save(model,'customer_buy.pt')

In [59]:
!ls

customer_buy.pt  sample_data


In [60]:
restored_model = torch.load('customer_buy.pt')

In [61]:
y_cust_pred_0 = restored_model(torch.from_numpy(np.array([[98,97,1,0,1,4.832334122511638,7,282.97659001640096]])).float())
y_cust_pred_0

tensor([[-0.7443, -0.6445]], grad_fn=<LogSoftmaxBackward0>)

In [62]:
_, predicted_y_cust_pred_0 = torch.max(y_cust_pred_0.data,-1)
predicted_y_cust_pred_0

tensor([1])

In [63]:
model.state_dict()

OrderedDict([('fc1.weight',
              tensor([[-4.7720e-02, -1.8021e-01,  2.3253e-02,  3.9389e-02,  3.7898e-02,
                       -8.0722e-02,  4.4313e-04, -1.5172e+00],
                      [-5.9666e-02,  4.6477e-02, -1.4066e-02, -7.7271e-02, -6.3147e-03,
                       -1.1119e-01,  3.0782e-02, -7.9491e-01],
                      [-8.0310e-02, -1.0845e-01, -6.6743e-03,  4.2425e-04, -2.7080e-02,
                       -4.1895e-02, -1.9653e-02, -9.8755e-01],
                      [-1.0126e-01, -1.9774e-01, -7.1519e-02,  1.7291e-01,  1.2950e-02,
                        1.4557e-02, -5.0437e-02, -6.0235e-01],
                      [ 3.0951e-01, -1.5368e-01,  1.0499e-01,  1.2032e-01,  1.7002e-01,
                       -1.6335e-01,  2.2171e-01, -4.5931e-01],
                      [-8.6656e-02, -5.0303e-01,  5.0244e-02,  3.0603e-01,  3.9032e-02,
                       -2.5225e-01,  1.6992e-02, -2.1472e-01],
                      [ 1.2138e-01, -6.3360e-02, -1.6369e-03, -1.0

In [64]:
torch.save(model.state_dict(),'customer_buy_state_dict')

In [72]:
inference_data = pd.read_csv("https://raw.githubusercontent.com/rajimitara/buildModel-and-Mlflow/main/data_inference.csv")

inference_data.head()

id_customer  age_customer  ...  n_transactions_last_month  volume_last_month
0         7327            98  ...                          7         282.976590
1         7340            31  ...                         15         270.036026
2         7355            48  ...                         13         189.150910
3         7360            77  ...                          9         146.414624
4         7372            77  ...                          7         111.098443

[5 rows x 9 columns]

In [73]:
X_inference = inference_data.iloc[:,1:].values

In [75]:
new_classifier_inference_file = model(torch.from_numpy(sc.transform(np.array(X_inference))).float())
new_classifier_inference_file

tensor([[-7.4432e-01, -6.4447e-01],
        [-4.6459e-01, -9.8992e-01],
        [-5.6939e-01, -8.3441e-01],
        ...,
        [-3.8598e-03, -5.5591e+00],
        [-1.9036e-03, -6.2649e+00],
        [-8.7368e-03, -4.7446e+00]], grad_fn=<LogSoftmaxBackward0>)

In [79]:
_, predicted_inferences= torch.max(new_classifier_inference_file.data,-1)
predicted_inferences

tensor([1, 0, 0,  ..., 0, 0, 0])

In [80]:
print(predicted_inferences)
np.savetxt('result.csv', predicted_inferences, delimiter=',')

tensor([1, 0, 0,  ..., 0, 0, 0])


In [65]:
!ls

customer_buy.pt  customer_buy_state_dict  sample_data


In [66]:
new_predictor = Net()

In [67]:
y_cust_pred_1 = restored_model(torch.from_numpy(np.array([[98,97,1,0,1,4.832334122511638,7,282.97659001640096]])).float())
y_cust_pred_1

tensor([[-0.7443, -0.6445]], grad_fn=<LogSoftmaxBackward0>)

In [68]:
!zip -r customer_buy_state_dict.zip customer_buy_state_dict

  adding: customer_buy_state_dict (deflated 41%)


In [69]:
!ls

customer_buy.pt		 customer_buy_state_dict.zip
customer_buy_state_dict  sample_data


In [70]:
from google.colab import files


In [71]:
files.download('customer_buy_state_dict.zip')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>